package ar.edu.unlu.oca.controlador;

public enum Eventos {
	COMENZAR_PARTIDA,
	FIN_JUEGO,
	JUGADOR_AGREGADO,
	LIMITE_JUGADORES,
	TURNO_TERMINADO,
	MOSTRAR_CASILLA_DADOS,
	TURNO_PERDIDO, ESTA_EN_POZO, TURNO_GANADO, JUGADOR_ELIMINADO, JUGADOR_PARTIDA_GUARDADA
}
